// Code generated by `monstera generate`. DO NOT EDIT.

package monsteraexample

import (
	"context"
	monstera "github.com/evrblk/monstera"
	corepb "github.com/evrblk/monstera-example/corepb"
	monsterax "github.com/evrblk/monstera/x"
	"sync"
)

type ExampleServiceMonsteraShardKeyCalculator interface {
	ListAccountsShardKey(request *corepb.ListAccountsRequest) []byte
	GetAccountShardKey(request *corepb.GetAccountRequest) []byte
	CreateAccountShardKey(request *corepb.CreateAccountRequest) []byte
	UpdateAccountShardKey(request *corepb.UpdateAccountRequest) []byte
	DeleteAccountShardKey(request *corepb.DeleteAccountRequest) []byte

	GetNamespaceShardKey(request *corepb.GetNamespaceRequest) []byte
	ListNamespacesShardKey(request *corepb.ListNamespacesRequest) []byte
	CreateNamespaceShardKey(request *corepb.CreateNamespaceRequest) []byte
	UpdateNamespaceShardKey(request *corepb.UpdateNamespaceRequest) []byte
	DeleteNamespaceShardKey(request *corepb.DeleteNamespaceRequest) []byte

	AcquireLockShardKey(request *corepb.AcquireLockRequest) []byte
	ReleaseLockShardKey(request *corepb.ReleaseLockRequest) []byte
	DeleteLockShardKey(request *corepb.DeleteLockRequest) []byte
	GetLockShardKey(request *corepb.GetLockRequest) []byte
}

type ExampleServiceCoreApiMonsteraStub struct {
	monsteraClient     *monstera.MonsteraClient
	shardKeyCalculator ExampleServiceMonsteraShardKeyCalculator
}

var _ ExampleServiceCoreApi = &ExampleServiceCoreApiMonsteraStub{}

func (s *ExampleServiceCoreApiMonsteraStub) ListAccounts(ctx context.Context, request *corepb.ListAccountsRequest) (*corepb.ListAccountsResponse, error) {
	readRequest := &corepb.ReadRequest{Request: &corepb.ReadRequest_ListAccountsRequest{ListAccountsRequest: request}}
	readResponse := &corepb.ReadResponse{}
	shardKey := s.shardKeyCalculator.ListAccountsShardKey(request)

	err := s.monsteraClient.Read(ctx, "Accounts", shardKey, false, readRequest, readResponse)
	if err != nil {
		return nil, err
	}

	response, ok := readResponse.Response.(*corepb.ReadResponse_ListAccountsResponse)
	if ok {
		return response.ListAccountsResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": readResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) GetAccount(ctx context.Context, request *corepb.GetAccountRequest) (*corepb.GetAccountResponse, error) {
	readRequest := &corepb.ReadRequest{Request: &corepb.ReadRequest_GetAccountRequest{GetAccountRequest: request}}
	readResponse := &corepb.ReadResponse{}
	shardKey := s.shardKeyCalculator.GetAccountShardKey(request)

	err := s.monsteraClient.Read(ctx, "Accounts", shardKey, false, readRequest, readResponse)
	if err != nil {
		return nil, err
	}

	response, ok := readResponse.Response.(*corepb.ReadResponse_GetAccountResponse)
	if ok {
		return response.GetAccountResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": readResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) CreateAccount(ctx context.Context, request *corepb.CreateAccountRequest) (*corepb.CreateAccountResponse, error) {
	updateRequest := &corepb.UpdateRequest{Request: &corepb.UpdateRequest_CreateAccountRequest{CreateAccountRequest: request}}
	updateResponse := &corepb.UpdateResponse{}
	shardKey := s.shardKeyCalculator.CreateAccountShardKey(request)

	err := s.monsteraClient.Update(ctx, "Accounts", shardKey, updateRequest, updateResponse)
	if err != nil {
		return nil, err
	}

	response, ok := updateResponse.Response.(*corepb.UpdateResponse_CreateAccountResponse)
	if ok {
		return response.CreateAccountResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": updateResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) UpdateAccount(ctx context.Context, request *corepb.UpdateAccountRequest) (*corepb.UpdateAccountResponse, error) {
	updateRequest := &corepb.UpdateRequest{Request: &corepb.UpdateRequest_UpdateAccountRequest{UpdateAccountRequest: request}}
	updateResponse := &corepb.UpdateResponse{}
	shardKey := s.shardKeyCalculator.UpdateAccountShardKey(request)

	err := s.monsteraClient.Update(ctx, "Accounts", shardKey, updateRequest, updateResponse)
	if err != nil {
		return nil, err
	}

	response, ok := updateResponse.Response.(*corepb.UpdateResponse_UpdateAccountResponse)
	if ok {
		return response.UpdateAccountResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": updateResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) DeleteAccount(ctx context.Context, request *corepb.DeleteAccountRequest) (*corepb.DeleteAccountResponse, error) {
	updateRequest := &corepb.UpdateRequest{Request: &corepb.UpdateRequest_DeleteAccountRequest{DeleteAccountRequest: request}}
	updateResponse := &corepb.UpdateResponse{}
	shardKey := s.shardKeyCalculator.DeleteAccountShardKey(request)

	err := s.monsteraClient.Update(ctx, "Accounts", shardKey, updateRequest, updateResponse)
	if err != nil {
		return nil, err
	}

	response, ok := updateResponse.Response.(*corepb.UpdateResponse_DeleteAccountResponse)
	if ok {
		return response.DeleteAccountResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": updateResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) GetNamespace(ctx context.Context, request *corepb.GetNamespaceRequest) (*corepb.GetNamespaceResponse, error) {
	readRequest := &corepb.ReadRequest{Request: &corepb.ReadRequest_GetNamespaceRequest{GetNamespaceRequest: request}}
	readResponse := &corepb.ReadResponse{}
	shardKey := s.shardKeyCalculator.GetNamespaceShardKey(request)

	err := s.monsteraClient.Read(ctx, "Namespaces", shardKey, false, readRequest, readResponse)
	if err != nil {
		return nil, err
	}

	response, ok := readResponse.Response.(*corepb.ReadResponse_GetNamespaceResponse)
	if ok {
		return response.GetNamespaceResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": readResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) ListNamespaces(ctx context.Context, request *corepb.ListNamespacesRequest) (*corepb.ListNamespacesResponse, error) {
	readRequest := &corepb.ReadRequest{Request: &corepb.ReadRequest_ListNamespacesRequest{ListNamespacesRequest: request}}
	readResponse := &corepb.ReadResponse{}
	shardKey := s.shardKeyCalculator.ListNamespacesShardKey(request)

	err := s.monsteraClient.Read(ctx, "Namespaces", shardKey, false, readRequest, readResponse)
	if err != nil {
		return nil, err
	}

	response, ok := readResponse.Response.(*corepb.ReadResponse_ListNamespacesResponse)
	if ok {
		return response.ListNamespacesResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": readResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) CreateNamespace(ctx context.Context, request *corepb.CreateNamespaceRequest) (*corepb.CreateNamespaceResponse, error) {
	updateRequest := &corepb.UpdateRequest{Request: &corepb.UpdateRequest_CreateNamespaceRequest{CreateNamespaceRequest: request}}
	updateResponse := &corepb.UpdateResponse{}
	shardKey := s.shardKeyCalculator.CreateNamespaceShardKey(request)

	err := s.monsteraClient.Update(ctx, "Namespaces", shardKey, updateRequest, updateResponse)
	if err != nil {
		return nil, err
	}

	response, ok := updateResponse.Response.(*corepb.UpdateResponse_CreateNamespaceResponse)
	if ok {
		return response.CreateNamespaceResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": updateResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) UpdateNamespace(ctx context.Context, request *corepb.UpdateNamespaceRequest) (*corepb.UpdateNamespaceResponse, error) {
	updateRequest := &corepb.UpdateRequest{Request: &corepb.UpdateRequest_UpdateNamespaceRequest{UpdateNamespaceRequest: request}}
	updateResponse := &corepb.UpdateResponse{}
	shardKey := s.shardKeyCalculator.UpdateNamespaceShardKey(request)

	err := s.monsteraClient.Update(ctx, "Namespaces", shardKey, updateRequest, updateResponse)
	if err != nil {
		return nil, err
	}

	response, ok := updateResponse.Response.(*corepb.UpdateResponse_UpdateNamespaceResponse)
	if ok {
		return response.UpdateNamespaceResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": updateResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) DeleteNamespace(ctx context.Context, request *corepb.DeleteNamespaceRequest) (*corepb.DeleteNamespaceResponse, error) {
	updateRequest := &corepb.UpdateRequest{Request: &corepb.UpdateRequest_DeleteNamespaceRequest{DeleteNamespaceRequest: request}}
	updateResponse := &corepb.UpdateResponse{}
	shardKey := s.shardKeyCalculator.DeleteNamespaceShardKey(request)

	err := s.monsteraClient.Update(ctx, "Namespaces", shardKey, updateRequest, updateResponse)
	if err != nil {
		return nil, err
	}

	response, ok := updateResponse.Response.(*corepb.UpdateResponse_DeleteNamespaceResponse)
	if ok {
		return response.DeleteNamespaceResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": updateResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) AcquireLock(ctx context.Context, request *corepb.AcquireLockRequest) (*corepb.AcquireLockResponse, error) {
	updateRequest := &corepb.UpdateRequest{Request: &corepb.UpdateRequest_AcquireLockRequest{AcquireLockRequest: request}}
	updateResponse := &corepb.UpdateResponse{}
	shardKey := s.shardKeyCalculator.AcquireLockShardKey(request)

	err := s.monsteraClient.Update(ctx, "Locks", shardKey, updateRequest, updateResponse)
	if err != nil {
		return nil, err
	}

	response, ok := updateResponse.Response.(*corepb.UpdateResponse_AcquireLockResponse)
	if ok {
		return response.AcquireLockResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": updateResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) ReleaseLock(ctx context.Context, request *corepb.ReleaseLockRequest) (*corepb.ReleaseLockResponse, error) {
	updateRequest := &corepb.UpdateRequest{Request: &corepb.UpdateRequest_ReleaseLockRequest{ReleaseLockRequest: request}}
	updateResponse := &corepb.UpdateResponse{}
	shardKey := s.shardKeyCalculator.ReleaseLockShardKey(request)

	err := s.monsteraClient.Update(ctx, "Locks", shardKey, updateRequest, updateResponse)
	if err != nil {
		return nil, err
	}

	response, ok := updateResponse.Response.(*corepb.UpdateResponse_ReleaseLockResponse)
	if ok {
		return response.ReleaseLockResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": updateResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) DeleteLock(ctx context.Context, request *corepb.DeleteLockRequest) (*corepb.DeleteLockResponse, error) {
	updateRequest := &corepb.UpdateRequest{Request: &corepb.UpdateRequest_DeleteLockRequest{DeleteLockRequest: request}}
	updateResponse := &corepb.UpdateResponse{}
	shardKey := s.shardKeyCalculator.DeleteLockShardKey(request)

	err := s.monsteraClient.Update(ctx, "Locks", shardKey, updateRequest, updateResponse)
	if err != nil {
		return nil, err
	}

	response, ok := updateResponse.Response.(*corepb.UpdateResponse_DeleteLockResponse)
	if ok {
		return response.DeleteLockResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": updateResponse.String()})
	}
}

func (s *ExampleServiceCoreApiMonsteraStub) GetLock(ctx context.Context, request *corepb.GetLockRequest) (*corepb.GetLockResponse, error) {
	updateRequest := &corepb.UpdateRequest{Request: &corepb.UpdateRequest_GetLockRequest{GetLockRequest: request}}
	updateResponse := &corepb.UpdateResponse{}
	shardKey := s.shardKeyCalculator.GetLockShardKey(request)

	err := s.monsteraClient.Update(ctx, "Locks", shardKey, updateRequest, updateResponse)
	if err != nil {
		return nil, err
	}

	response, ok := updateResponse.Response.(*corepb.UpdateResponse_GetLockResponse)
	if ok {
		return response.GetLockResponse, nil
	} else {
		return nil, monsterax.NewErrorWithContext(monsterax.Internal, "invalid response type", map[string]string{"response": updateResponse.String()})
	}
}

func NewExampleServiceCoreApiMonsteraStub(monsteraClient *monstera.MonsteraClient, shardKeyCalculator ExampleServiceMonsteraShardKeyCalculator) *ExampleServiceCoreApiMonsteraStub {
	return &ExampleServiceCoreApiMonsteraStub{monsteraClient: monsteraClient, shardKeyCalculator: shardKeyCalculator}
}

type ExampleServiceCoreApiStandaloneStub struct {
	accountsCore   AccountsCoreApi
	namespacesCore NamespacesCoreApi
	locksCore      LocksCoreApi

	mu sync.RWMutex
}

func (s *ExampleServiceCoreApiStandaloneStub) ListAccounts(ctx context.Context, request *corepb.ListAccountsRequest) (*corepb.ListAccountsResponse, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	return s.accountsCore.ListAccounts(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) GetAccount(ctx context.Context, request *corepb.GetAccountRequest) (*corepb.GetAccountResponse, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	return s.accountsCore.GetAccount(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) CreateAccount(ctx context.Context, request *corepb.CreateAccountRequest) (*corepb.CreateAccountResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.accountsCore.CreateAccount(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) UpdateAccount(ctx context.Context, request *corepb.UpdateAccountRequest) (*corepb.UpdateAccountResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.accountsCore.UpdateAccount(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) DeleteAccount(ctx context.Context, request *corepb.DeleteAccountRequest) (*corepb.DeleteAccountResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.accountsCore.DeleteAccount(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) GetNamespace(ctx context.Context, request *corepb.GetNamespaceRequest) (*corepb.GetNamespaceResponse, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	return s.namespacesCore.GetNamespace(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) ListNamespaces(ctx context.Context, request *corepb.ListNamespacesRequest) (*corepb.ListNamespacesResponse, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	return s.namespacesCore.ListNamespaces(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) CreateNamespace(ctx context.Context, request *corepb.CreateNamespaceRequest) (*corepb.CreateNamespaceResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.namespacesCore.CreateNamespace(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) UpdateNamespace(ctx context.Context, request *corepb.UpdateNamespaceRequest) (*corepb.UpdateNamespaceResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.namespacesCore.UpdateNamespace(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) DeleteNamespace(ctx context.Context, request *corepb.DeleteNamespaceRequest) (*corepb.DeleteNamespaceResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.namespacesCore.DeleteNamespace(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) AcquireLock(ctx context.Context, request *corepb.AcquireLockRequest) (*corepb.AcquireLockResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.locksCore.AcquireLock(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) ReleaseLock(ctx context.Context, request *corepb.ReleaseLockRequest) (*corepb.ReleaseLockResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.locksCore.ReleaseLock(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) DeleteLock(ctx context.Context, request *corepb.DeleteLockRequest) (*corepb.DeleteLockResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.locksCore.DeleteLock(request)
}

func (s *ExampleServiceCoreApiStandaloneStub) GetLock(ctx context.Context, request *corepb.GetLockRequest) (*corepb.GetLockResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.locksCore.GetLock(request)
}

func NewExampleServiceCoreApiStandaloneStub(accountsCore AccountsCoreApi, namespacesCore NamespacesCoreApi, locksCore LocksCoreApi) *ExampleServiceCoreApiStandaloneStub {
	return &ExampleServiceCoreApiStandaloneStub{accountsCore: accountsCore, namespacesCore: namespacesCore, locksCore: locksCore}
}
