// Code generated by `monstera generate`. DO NOT EDIT.

package tinyurl

import (
	"context"
	monstera "github.com/evrblk/monstera"
	corepb "github.com/evrblk/monstera-example/tinyurl/corepb"
	"io"
)

type TinyUrlServiceCoreApi interface {
	GetShortUrl(ctx context.Context, request *corepb.GetShortUrlRequest) (*corepb.GetShortUrlResponse, error)
	ListShortUrls(ctx context.Context, request *corepb.ListShortUrlsRequest) (*corepb.ListShortUrlsResponse, error)
	CreateShortUrl(ctx context.Context, request *corepb.CreateShortUrlRequest) (*corepb.CreateShortUrlResponse, error)

	GetUser(ctx context.Context, request *corepb.GetUserRequest) (*corepb.GetUserResponse, error)
	CreateUser(ctx context.Context, request *corepb.CreateUserRequest) (*corepb.CreateUserResponse, error)
}

var _ TinyUrlServiceCoreApi = &UnimplementedTinyUrlServiceCoreApi{}

type UnimplementedTinyUrlServiceCoreApi struct{}

func (a *UnimplementedTinyUrlServiceCoreApi) GetShortUrl(ctx context.Context, request *corepb.GetShortUrlRequest) (*corepb.GetShortUrlResponse, error) {
	panic("not implemented")
}

func (a *UnimplementedTinyUrlServiceCoreApi) ListShortUrls(ctx context.Context, request *corepb.ListShortUrlsRequest) (*corepb.ListShortUrlsResponse, error) {
	panic("not implemented")
}

func (a *UnimplementedTinyUrlServiceCoreApi) CreateShortUrl(ctx context.Context, request *corepb.CreateShortUrlRequest) (*corepb.CreateShortUrlResponse, error) {
	panic("not implemented")
}

func (a *UnimplementedTinyUrlServiceCoreApi) GetUser(ctx context.Context, request *corepb.GetUserRequest) (*corepb.GetUserResponse, error) {
	panic("not implemented")
}

func (a *UnimplementedTinyUrlServiceCoreApi) CreateUser(ctx context.Context, request *corepb.CreateUserRequest) (*corepb.CreateUserResponse, error) {
	panic("not implemented")
}

type ShortUrlsCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(reader io.ReadCloser) error
	Close()
	GetShortUrl(request *corepb.GetShortUrlRequest) (*corepb.GetShortUrlResponse, error)
	ListShortUrls(request *corepb.ListShortUrlsRequest) (*corepb.ListShortUrlsResponse, error)
	CreateShortUrl(request *corepb.CreateShortUrlRequest) (*corepb.CreateShortUrlResponse, error)
}

type UsersCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(reader io.ReadCloser) error
	Close()
	GetUser(request *corepb.GetUserRequest) (*corepb.GetUserResponse, error)
	CreateUser(request *corepb.CreateUserRequest) (*corepb.CreateUserResponse, error)
}
