node01: go run ./cmd/node --port=7000 --node-id=nd_262ad32 --data-dir=./data/nd_262ad32 --monstera-config=./cluster_config.pb
node02: go run ./cmd/node --port=7001 --node-id=nd_bf6ad02f --data-dir=./data/nd_bf6ad02f --monstera-config=./cluster_config.pb
node03: go run ./cmd/node --port=7002 --node-id=nd_144761d4 --data-dir=./data/nd_144761d4 --monstera-config=./cluster_config.pb

gateway: go run ./cmd/gateway --port=8000 --monstera-config=./cluster_config.pb
