// Code generated by `monstera generate`. DO NOT EDIT.

package ledger

import (
	"context"
	monstera "github.com/evrblk/monstera"
	corepb "github.com/evrblk/monstera-example/ledger/corepb"
	"io"
)

type LedgerServiceCoreApi interface {
	ListTransactions(ctx context.Context, request *corepb.ListTransactionsRequest) (*corepb.ListTransactionsResponse, error)
	GetTransaction(ctx context.Context, request *corepb.GetTransactionRequest) (*corepb.GetTransactionResponse, error)
	GetAccount(ctx context.Context, request *corepb.GetAccountRequest) (*corepb.GetAccountResponse, error)
	CreateTransaction(ctx context.Context, request *corepb.CreateTransactionRequest) (*corepb.CreateTransactionResponse, error)
	CancelTransaction(ctx context.Context, request *corepb.CancelTransactionRequest) (*corepb.CancelTransactionResponse, error)
	SettleTransaction(ctx context.Context, request *corepb.SettleTransactionRequest) (*corepb.SettleTransactionResponse, error)
	CreateAccount(ctx context.Context, request *corepb.CreateAccountRequest) (*corepb.CreateAccountResponse, error)
}

var _ LedgerServiceCoreApi = &UnimplementedLedgerServiceCoreApi{}

type UnimplementedLedgerServiceCoreApi struct{}

func (a *UnimplementedLedgerServiceCoreApi) ListTransactions(ctx context.Context, request *corepb.ListTransactionsRequest) (*corepb.ListTransactionsResponse, error) {
	panic("not implemented")
}

func (a *UnimplementedLedgerServiceCoreApi) GetTransaction(ctx context.Context, request *corepb.GetTransactionRequest) (*corepb.GetTransactionResponse, error) {
	panic("not implemented")
}

func (a *UnimplementedLedgerServiceCoreApi) GetAccount(ctx context.Context, request *corepb.GetAccountRequest) (*corepb.GetAccountResponse, error) {
	panic("not implemented")
}

func (a *UnimplementedLedgerServiceCoreApi) CreateTransaction(ctx context.Context, request *corepb.CreateTransactionRequest) (*corepb.CreateTransactionResponse, error) {
	panic("not implemented")
}

func (a *UnimplementedLedgerServiceCoreApi) CancelTransaction(ctx context.Context, request *corepb.CancelTransactionRequest) (*corepb.CancelTransactionResponse, error) {
	panic("not implemented")
}

func (a *UnimplementedLedgerServiceCoreApi) SettleTransaction(ctx context.Context, request *corepb.SettleTransactionRequest) (*corepb.SettleTransactionResponse, error) {
	panic("not implemented")
}

func (a *UnimplementedLedgerServiceCoreApi) CreateAccount(ctx context.Context, request *corepb.CreateAccountRequest) (*corepb.CreateAccountResponse, error) {
	panic("not implemented")
}

type AccountsCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(reader io.ReadCloser) error
	Close()
	ListTransactions(request *corepb.ListTransactionsRequest) (*corepb.ListTransactionsResponse, error)
	GetTransaction(request *corepb.GetTransactionRequest) (*corepb.GetTransactionResponse, error)
	GetAccount(request *corepb.GetAccountRequest) (*corepb.GetAccountResponse, error)
	CreateTransaction(request *corepb.CreateTransactionRequest) (*corepb.CreateTransactionResponse, error)
	CancelTransaction(request *corepb.CancelTransactionRequest) (*corepb.CancelTransactionResponse, error)
	SettleTransaction(request *corepb.SettleTransactionRequest) (*corepb.SettleTransactionResponse, error)
	CreateAccount(request *corepb.CreateAccountRequest) (*corepb.CreateAccountResponse, error)
}
