node01: go run ./cmd/node --port=7000 --node-id=nd_b46208f3 --data-dir=./data/nd_b46208f3 --monstera-config=./cluster_config.pb
node02: go run ./cmd/node --port=7001 --node-id=nd_6417411c --data-dir=./data/nd_6417411c --monstera-config=./cluster_config.pb
node03: go run ./cmd/node --port=7002 --node-id=nd_9eccdbe --data-dir=./data/nd_9eccdbe --monstera-config=./cluster_config.pb

gateway: go run ./cmd/gateway --port=8000 --monstera-config=./cluster_config.pb
